name: Linux_Container_Workflow
on:
  push:
    branches:
    - 'DEVOPS-*'

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        outputs:
          image_tag:  ${{ steps.image_tag.outputs.image_tag_output }}
        steps:
        # ACTION: Checkout repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@v3
        # ACTION: Build Docker Image
        - name: 'Build Docker Image'
          uses: ./.github/actions/a_composite002@v1
          with:
            aci_resource_group: "sergiu_acr_poc"
            aci_container_name: "createdbygithubaction"
            aci_container_dnslabel: "bdianddacipoc"
            aci_container_region: "eastus2"
            app_source_directory: 'composire002'