name: 'Build Docker Image'
description: 'Build Docker Image'
inputs:
  app_source_directory:
    description: 'Dockerfile location'
    required: true
    default: './composire002'
outputs:
  date:
    description: "Get Current date and time"
    value: ${{ steps.get_date.outputs.date }}
runs:
  using: "composite"
  steps:
  # Get date and time to use in image tag
  - name: 'Get current date'
    id: get_date
    run: echo "::set-output name=date::$(date +'%Y-%m-%d_%H_%M_%S')"
  # Build image based on Dockerfile and puch to ACR
  - name: 'Build base image'
    run: docker build ./${{ env.APP_SOURCE_DIRECTORY }} -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/sampleapp:${{ github.sha }}-${{ steps.get_date.outputs.date }}
  - name: 'Docker Login with Azure SP'
    run: echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login -u ${{ secrets.REGISTRY_USERNAME }} ${{ secrets.REGISTRY_LOGIN_SERVER }} --password-stdin
  - name: 'Push image to ACR'
    run: docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/sampleapp:${{ github.sha }}-${{ steps.get_date.outputs.date }}
  - name: 'Output image tag'
    id: image_tag
    run: echo "::set-output name=image_tag_output::${{ github.sha }}-${{ steps.get_date.outputs.date }}"