name: "Sign"
description: 'Sign files with Relativity certificate'
inputs:
  SigningAppRegistrationId:
    description: 'SP ID'
    required: true
  SigningAppRegistrationSecretKey:
    description: 'SP Key'
    required: true
  SigningAppRegistrationTenantId:
    description: 'SP Tenant ID'
    required: true
  FilesToSignPath:
    description: 'Path to text file of list of files to sign. By default, signs everything in Artifacts'
    required: false

runs:
  using: "composite"
  steps:
  - name: Build Signing File
    if: inputs.FilesToSignPath == ''
    shell: pwsh
    run: |
        # If no signing file passed, build one with contents of the Artifacts folder
        $artifactsPath = Join-Path $env:GITHUB_WORKSPACE "Artifacts"
        $fileList = Get-ChildItem -Recurse $artifactsPath -Include *.dll, *.msi, *.exe | Resolve-Path -Relative
        Out-File -FilePath FilesToSign.txt -InputObject $fileList
  - name: Sign Files
    shell: pwsh
    run: |
        $scriptPath = Resolve-Path "${{github.action_path}}\Invoke-Sign.ps1"
        . $scriptPath
        if ('${{inputs.FilesToSignPath}}' -eq '')
        {
          $filepath = Join-Path $env:GITHUB_WORKSPACE FilesToSign.txt
        }
        else
        {
          $filepath = Join-Path $env:GITHUB_WORKSPACE ${{inputs.FilesToSignPath}}
        }
        Invoke-Sign `
          -SigningAppRegistrationId ${{inputs.SigningAppRegistrationId}} `
          -SigningAppRegistrationSecretKey ${{inputs.SigningAppRegistrationSecretKey}} `
          -SigningAppRegistrationTenantID ${{inputs.SigningAppRegistrationTenantId}} `
          -FilesToSignPath $filepath