on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3
      - run: pwd
        shell: bash
      - id: my_action
        uses: ./.github/actions/a_composite001@v1
        with:
          who-to-greet: 'Mona the Octocat'
      - run: echo random-number ${{ steps.my_action.outputs.random-number }}
        shell: bash